mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('welcome.urls')),
    path('admin/', admin.site.urls),
]

welcome/urls.py
from django.urls import path
from welcome.views import welcome_page, BMI, retirement
from . import views

app_name = 'welcome'

urlpatterns = [
    path("", views.welcome_page, name="home"),
    path("bmi_calculator/", views.BMI, name="bmi_cal"),
    path("retirement_calculator/", views.retirement, name="retire"),
]


welcome/models.py
from django.db import models

# Create your models here.

welcome/forms.py
from django import forms

#class HomeForm(forms.Form):

class BMIForms(forms.Form):
    feet = forms.IntegerField(required=True)
    inches = forms.IntegerField(required=True)
    weight = forms.FloatField(required=True)


class RetirementForms(forms.Form):
    age = forms.IntegerField(required=True)
    salary = forms.IntegerField(required=True)
    savings = forms.FloatField(required=True)
    goal = forms.IntegerField(required=True)

welcome/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import BMIForms
from .forms import RetirementForms

# Create your views here.
#class HomePage(TemplateView):
template_name = 'welcome/home.html'
def welcome_page(request):

    return render(request=request,
    template_name=template_name)
    


def BMI(request):
    form = BMIForms(request.POST)
    results = ""


    if form.is_valid():
        input_ft = form.cleaned_data['feet']
        input_in = form.cleaned_data['inches']
        input_lbs = form.cleaned_data['weight']

        

        w = input_lbs * 0.45
        i = (input_ft * 12) + input_in
        inch = (i * 0.025) * (i * 0.025)
        bmi = w / inch
        bmi = format(bmi, '.1f')
        bmi = float(bmi)

        if bmi < 18.5:
            results = "BMI is {} - Underweight" .format(bmi)
        elif bmi > 18.5 and bmi < 24.9:
            results = "BMI is {} - Normal Weight" .format(bmi)
        elif bmi > 25.0 and bmi < 29.9:
            results = "BMI is {} - Overweight" .format(bmi)
        else:
            results = "BMI is {} - Obese" .format(bmi)

    
        form = BMIForms()
    args = {"form":form, 'results':results}
    return render(request = request,
                    template_name= "welcome/bmi_calculator.html",
                    context=args )

def retirement(request):
    form = RetirementForms(request.POST)
    year_met = ""

    if form.is_valid():
        input_age = form.cleaned_data['age']
        input_sal = form.cleaned_data['salary']
        input_savings = form.cleaned_data['savings']
        input_goal = form.cleaned_data['goal']


        savings_per_year = (input_sal * input_savings) * 1.35
        years_till = input_goal / savings_per_year
        age_met = input_age + years_till
        age_met = round(age_met)

        
        if age_met < 100:
            year_met = "Goal will be met at age: {}" .format(age_met)
        else:
            year_met = "The goal will not be met: {}" .format(age_met)
    
        form = RetirementForms()
        
    args = {"form":form, "year_met":year_met}
    return render(request = request,
                    template_name= "welcome/retirement_calculator.html",
                    context=args)

welcome/templates/welcome/bmi_calculator.html
{% block content %}

<h1>BMI Calculator</h1>

<br/>
<br/>

<form action="" method="POST">
    

    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" name="submit" required id ="id_submit">Submit</button>
    
    <p><a href="{% url 'welcome:home' %}">Home</a></p>
    <h3>{{results}}</h3>

</form>

<br/>



{% endblock %}

welcome/templates/welcome/home.html

{% block content %}

    <h1>Click on one of the two buttons to select one of the calculators</h1>
    <div class="container">
        <form method="POST">
            {% csrf_token %}   
            {{form.as_p}}  
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit" name="bmi_cal" formaction="{% url 'welcome:bmi_cal' %}">
                BMI Calculator
            </button>
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit" name="retire" formaction="{% url 'welcome:retire' %}">
                Retirement
            </button>
        </form>
    </div>
{% endblock %}

welcome/templates/welcome/retirement_calculator.html
{% block content %}

<h1>Retirement Calculator</h1>

<br/>
<br/>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" name="submit">Submit</button>
    <p><a href="{% url 'welcome:home' %}">Home</a></p>

    <h3>{{year_met}}</h3>
</form>

<br/>



{% endblock %}